version: '3.8'

services:
  streamlit:
    container_name: streamlit-ui
    #image: test:latest
    build:
      dockerfile: /deployment/streamlit_ui/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models

  listener:
    container_name: listener-endpoint
    #image: test:latest
    build:
      dockerfile: /deployment/listener_endpoint/Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./models:/app/models