version: '3.8'

services:
  streamlit:
    container_name: streamlit-ui
    #image: test:latest
    build:
      dockerfile: /deployment/streamlit-ui/Dockerfile
    ports:
      - "8501:8501"
#    volumes:
#      - ./streamlit-ui:/app

  listener:
    container_name: listener-endpoint
    #image: test:latest
    build:
      dockerfile: /deployment/listener-endpoint/Dockerfile
    ports:
      - 8081:8081
    #volumes:
    #  - ./listener-endpoint:/app