appName: My Wallet Manager
scriptName: my_wallet_manager
appVersion: 1.0.0
appDescription: My Wallet Manager is a simple application to manage your wallet.
appAuthor: Jorge Tarancón Rey

logs:
  path: ../logs

GoogleSheets:
  credentials:
    path: ./config/google_sheets_credentials.json
  spreadsheetName: Mock_Cartera_de_acciones

Models:
  path: ./models