name: Retrain model if there are changes in Google Sheets

on:
  schedule:
    - cron: '0 9 5 * *' # Run every 5th day of the month at 9:00 UTC

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.9'

    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        pip install pylint
        poetry config virtualenvs.create false

    - name: Install dependencies for listener_endpoint component
      working-directory: ./listener_endpoint
      run: |
        poetry install

    - name: Install dependencies for streamlit_ui component
      working-directory: ./streamlit_ui
      run: |
        poetry install

    - name: Retrain model
      working-directory: ./model_trainer
      env:
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      run: python app.py # Aqui en este script deberia ir la logica para
      # reentrenar el modelo
