name: Retrain model

on:
  schedule:
    - cron: '50 17 10 * *' # Run every 10th day of the month at 17:50 UTC

jobs:
  retrain-model:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.9'

    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false

    - name: Install dependencies for model_trainer component
      working-directory: ./model_trainer
      run: |
        poetry install

    - name: Retrain model
      env:
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      run: python model_trainer/src/app.py
