name: Retrain model

#on:
  #schedule:
    #- cron: '57 16 10 * *' # Run every 10th day of the month at 16:57 UTC
on: [push]

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.9'

    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false

    - name: Install dependencies for listener_endpoint component
      working-directory: ./model_trainer
      run: |
        poetry install

    - name: Retrain model
      env:
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      run: python model_trainer/src/app.py
